FROM mazamascience/spatialutils:0.8.6
LABEL maintainer="Jonathan Callahan jonathan.s.callahan@gmail.com"

RUN installGithub.r \
    MazamaScience/MazamaCoreUtils@0.5.2 \
    MazamaScience/MazamaLocationUtils@0.4.4 \
    MazamaScience/MazamaTimeSeries@0.3.0 \
    MazamaScience/AirMonitor@0.4.2 \
    MazamaScience/AirSensor2@0.5.3

