FROM mazamascience/spatialutils:0.8.6
MAINTAINER "Jonathan Callahan" jonathan.s.callahan@gmail.com

RUN installGithub.r \
    MazamaScience/MazamaLocationUtils@0.3.11 \
    MazamaScience/MazamaTimeSeries@0.2.15 \
    MazamaScience/AirMonitor@0.3.12 \
    MazamaScience/AirSensor2@0.3.7
